# Update the NODE_VERSION arg in docker-compose.yml to pick a Node version: 10, 12, 14
FROM  klakegg/hugo:0.75.1-ext-ubuntu

# Hugo dev server port
EXPOSE 1313

# ENTRYPOINT [ "server" ]
# [Optional] Uncomment this section to install additional OS packages you may want.
#
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment if you want to install more global node packages
# RUN sudo -u node npm install -g <your-package-list-here>
